/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PartnerLoginRouteImport } from './routes/partner-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisitorPhysicalVisitRouteImport } from './routes/visitor.physical-visit'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedTeamGuideRouteImport } from './routes/_authenticated.team-guide'
import { Route as AuthenticatedSftTrainingRouteImport } from './routes/_authenticated.sft-training'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated.partner'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated.learn'
import { Route as AuthenticatedFoodcostRouteImport } from './routes/_authenticated.foodcost'
import { Route as AuthenticatedCourseRouteImport } from './routes/_authenticated.course'
import { Route as AuthenticatedSftTrainingIndexRouteImport } from './routes/_authenticated.sft-training.index'
import { Route as AuthenticatedPartnerIndexRouteImport } from './routes/_authenticated.partner.index'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated.learn.index'
import { Route as AuthenticatedFoodcostIndexRouteImport } from './routes/_authenticated.foodcost.index'
import { Route as AuthenticatedSftTrainingReviewRouteImport } from './routes/_authenticated.sft-training.review'
import { Route as AuthenticatedSftTrainingProgramRouteImport } from './routes/_authenticated.sft-training.program'
import { Route as AuthenticatedSftTrainingPhysicalVisitRouteImport } from './routes/_authenticated.sft-training.physical-visit'
import { Route as AuthenticatedSftTrainingPartnerPaymentsRouteImport } from './routes/_authenticated.sft-training.partner-payments'
import { Route as AuthenticatedSftTrainingInviteCertifyRouteImport } from './routes/_authenticated.sft-training.invite-certify'
import { Route as AuthenticatedPartnerVisitRouteImport } from './routes/_authenticated.partner.visit'
import { Route as AuthenticatedPartnerLearnRouteImport } from './routes/_authenticated.partner.learn'
import { Route as AuthenticatedPartnerDownloadsRouteImport } from './routes/_authenticated.partner.downloads'
import { Route as AuthenticatedPartnerCookRouteImport } from './routes/_authenticated.partner.cook'
import { Route as AuthenticatedLearnCourseIdRouteImport } from './routes/_authenticated.learn.$courseId'
import { Route as AuthenticatedFoodcostUsRouteImport } from './routes/_authenticated.foodcost.us'
import { Route as AuthenticatedFoodcostInRouteImport } from './routes/_authenticated.foodcost.in'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedSftTrainingTeachCourseIdRouteImport } from './routes/_authenticated.sft-training.teach.$courseId'
import { Route as AuthenticatedSftTrainingPlayCourseIdRouteImport } from './routes/_authenticated.sft-training.play.$courseId'
import { Route as AuthenticatedSftTrainingCoursesCourseIdRouteImport } from './routes/_authenticated.sft-training.courses.$courseId'
import { Route as AuthenticatedLearnCourseIdModuleIdRouteImport } from './routes/_authenticated.learn.$courseId.$moduleId'
import { Route as AuthenticatedFoodcostUsReportsHubRouteImport } from './routes/_authenticated.foodcost.us.reports-hub'
import { Route as AuthenticatedFoodcostUsReportsRouteImport } from './routes/_authenticated.foodcost.us.reports'
import { Route as AuthenticatedFoodcostUsRecipeVerifyRouteImport } from './routes/_authenticated.foodcost.us.recipe-verify'
import { Route as AuthenticatedFoodcostUsProductsRouteImport } from './routes/_authenticated.foodcost.us.products'
import { Route as AuthenticatedFoodcostUsPrepsRouteImport } from './routes/_authenticated.foodcost.us.preps'
import { Route as AuthenticatedFoodcostUsPrepReportsRouteImport } from './routes/_authenticated.foodcost.us.prep-reports'
import { Route as AuthenticatedFoodcostUsPackingRouteImport } from './routes/_authenticated.foodcost.us.packing'
import { Route as AuthenticatedFoodcostUsNutriAuditRouteImport } from './routes/_authenticated.foodcost.us.nutri-audit'
import { Route as AuthenticatedFoodcostUsMissingRecipesRouteImport } from './routes/_authenticated.foodcost.us.missing-recipes'
import { Route as AuthenticatedFoodcostUsMenuCostingRouteImport } from './routes/_authenticated.foodcost.us.menu-costing'
import { Route as AuthenticatedFoodcostUsMenuRouteImport } from './routes/_authenticated.foodcost.us.menu'
import { Route as AuthenticatedFoodcostUsIngredientsRouteImport } from './routes/_authenticated.foodcost.us.ingredients'
import { Route as AuthenticatedFoodcostUsFcAuditRouteImport } from './routes/_authenticated.foodcost.us.fc-audit'
import { Route as AuthenticatedFoodcostUsCategoriesRouteImport } from './routes/_authenticated.foodcost.us.categories'
import { Route as AuthenticatedFoodcostUsBrandsRouteImport } from './routes/_authenticated.foodcost.us.brands'
import { Route as AuthenticatedFoodcostUsBrandMasterRouteImport } from './routes/_authenticated.foodcost.us.brand-master'
import { Route as AuthenticatedFoodcostUsAuditRouteImport } from './routes/_authenticated.foodcost.us.audit'
import { Route as AuthenticatedFoodcostRecipesRecipeIdRouteImport } from './routes/_authenticated.foodcost.recipes.$recipeId'
import { Route as AuthenticatedFoodcostPrepsIdRouteImport } from './routes/_authenticated.foodcost.preps.$id'
import { Route as AuthenticatedFoodcostInReportsHubRouteImport } from './routes/_authenticated.foodcost.in.reports-hub'
import { Route as AuthenticatedFoodcostInReportsRouteImport } from './routes/_authenticated.foodcost.in.reports'
import { Route as AuthenticatedFoodcostInRecipeVerifyRouteImport } from './routes/_authenticated.foodcost.in.recipe-verify'
import { Route as AuthenticatedFoodcostInProductsRouteImport } from './routes/_authenticated.foodcost.in.products'
import { Route as AuthenticatedFoodcostInPrepsRouteImport } from './routes/_authenticated.foodcost.in.preps'
import { Route as AuthenticatedFoodcostInPrepReportsRouteImport } from './routes/_authenticated.foodcost.in.prep-reports'
import { Route as AuthenticatedFoodcostInPackingRouteImport } from './routes/_authenticated.foodcost.in.packing'
import { Route as AuthenticatedFoodcostInNutriAuditRouteImport } from './routes/_authenticated.foodcost.in.nutri-audit'
import { Route as AuthenticatedFoodcostInMissingRecipesRouteImport } from './routes/_authenticated.foodcost.in.missing-recipes'
import { Route as AuthenticatedFoodcostInMenuCostingRouteImport } from './routes/_authenticated.foodcost.in.menu-costing'
import { Route as AuthenticatedFoodcostInMenuRouteImport } from './routes/_authenticated.foodcost.in.menu'
import { Route as AuthenticatedFoodcostInIngredientsRouteImport } from './routes/_authenticated.foodcost.in.ingredients'
import { Route as AuthenticatedFoodcostInFcAuditRouteImport } from './routes/_authenticated.foodcost.in.fc-audit'
import { Route as AuthenticatedFoodcostInCategoriesRouteImport } from './routes/_authenticated.foodcost.in.categories'
import { Route as AuthenticatedFoodcostInBrandsRouteImport } from './routes/_authenticated.foodcost.in.brands'
import { Route as AuthenticatedFoodcostInBrandMasterRouteImport } from './routes/_authenticated.foodcost.in.brand-master'
import { Route as AuthenticatedFoodcostInAuditRouteImport } from './routes/_authenticated.foodcost.in.audit'
import { Route as AuthenticatedSftTrainingPhysicalVisitAssignVisitIdRouteImport } from './routes/_authenticated.sft-training.physical-visit.assign.$visitId'
import { Route as AuthenticatedLearnCourseIdDayDayIdRouteImport } from './routes/_authenticated.learn.$courseId.day.$dayId'
import { Route as AuthenticatedFoodcostCategoriesIdCrcRouteImport } from './routes/_authenticated.foodcost.categories.$id.crc'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/partner-login',
  path: '/partner-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorPhysicalVisitRoute = VisitorPhysicalVisitRouteImport.update({
  id: '/visitor/physical-visit',
  path: '/visitor/physical-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamGuideRoute = AuthenticatedTeamGuideRouteImport.update({
  id: '/team-guide',
  path: '/team-guide',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSftTrainingRoute =
  AuthenticatedSftTrainingRouteImport.update({
    id: '/sft-training',
    path: '/sft-training',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFoodcostRoute = AuthenticatedFoodcostRouteImport.update({
  id: '/foodcost',
  path: '/foodcost',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCourseRoute = AuthenticatedCourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSftTrainingIndexRoute =
  AuthenticatedSftTrainingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSftTrainingRoute,
  } as any)
const AuthenticatedPartnerIndexRoute =
  AuthenticatedPartnerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedFoodcostIndexRoute =
  AuthenticatedFoodcostIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFoodcostRoute,
  } as any)
const AuthenticatedSftTrainingReviewRoute =
  AuthenticatedSftTrainingReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedSftTrainingRoute,
  } as any)
const AuthenticatedSftTrainingProgramRoute =
  AuthenticatedSftTrainingProgramRouteImport.update({
    id: '/program',
    path: '/program',
    getParentRoute: () => AuthenticatedSftTrainingRoute,
  } as any)
const AuthenticatedSftTrainingPhysicalVisitRoute =
  AuthenticatedSftTrainingPhysicalVisitRouteImport.update({
    id: '/physical-visit',
    path: '/physical-visit',
    getParentRoute: () => AuthenticatedSftTrainingRoute,
  } as any)
const AuthenticatedSftTrainingPartnerPaymentsRoute =
  AuthenticatedSftTrainingPartnerPaymentsRouteImport.update({
    id: '/partner-payments',
    path: '/partner-payments',
    getParentRoute: () => AuthenticatedSftTrainingRoute,
  } as any)
const AuthenticatedSftTrainingInviteCertifyRoute =
  AuthenticatedSftTrainingInviteCertifyRouteImport.update({
    id: '/invite-certify',
    path: '/invite-certify',
    getParentRoute: () => AuthenticatedSftTrainingRoute,
  } as any)
const AuthenticatedPartnerVisitRoute =
  AuthenticatedPartnerVisitRouteImport.update({
    id: '/visit',
    path: '/visit',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerLearnRoute =
  AuthenticatedPartnerLearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerDownloadsRoute =
  AuthenticatedPartnerDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerCookRoute =
  AuthenticatedPartnerCookRouteImport.update({
    id: '/cook',
    path: '/cook',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedLearnCourseIdRoute =
  AuthenticatedLearnCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedLearnRoute,
  } as any)
const AuthenticatedFoodcostUsRoute = AuthenticatedFoodcostUsRouteImport.update({
  id: '/us',
  path: '/us',
  getParentRoute: () => AuthenticatedFoodcostRoute,
} as any)
const AuthenticatedFoodcostInRoute = AuthenticatedFoodcostInRouteImport.update({
  id: '/in',
  path: '/in',
  getParentRoute: () => AuthenticatedFoodcostRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSftTrainingTeachCourseIdRoute =
  AuthenticatedSftTrainingTeachCourseIdRouteImport.update({
    id: '/teach/$courseId',
    path: '/teach/$courseId',
    getParentRoute: () => AuthenticatedSftTrainingRoute,
  } as any)
const AuthenticatedSftTrainingPlayCourseIdRoute =
  AuthenticatedSftTrainingPlayCourseIdRouteImport.update({
    id: '/play/$courseId',
    path: '/play/$courseId',
    getParentRoute: () => AuthenticatedSftTrainingRoute,
  } as any)
const AuthenticatedSftTrainingCoursesCourseIdRoute =
  AuthenticatedSftTrainingCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedSftTrainingRoute,
  } as any)
const AuthenticatedLearnCourseIdModuleIdRoute =
  AuthenticatedLearnCourseIdModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => AuthenticatedLearnCourseIdRoute,
  } as any)
const AuthenticatedFoodcostUsReportsHubRoute =
  AuthenticatedFoodcostUsReportsHubRouteImport.update({
    id: '/reports-hub',
    path: '/reports-hub',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsReportsRoute =
  AuthenticatedFoodcostUsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsRecipeVerifyRoute =
  AuthenticatedFoodcostUsRecipeVerifyRouteImport.update({
    id: '/recipe-verify',
    path: '/recipe-verify',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsProductsRoute =
  AuthenticatedFoodcostUsProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsPrepsRoute =
  AuthenticatedFoodcostUsPrepsRouteImport.update({
    id: '/preps',
    path: '/preps',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsPrepReportsRoute =
  AuthenticatedFoodcostUsPrepReportsRouteImport.update({
    id: '/prep-reports',
    path: '/prep-reports',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsPackingRoute =
  AuthenticatedFoodcostUsPackingRouteImport.update({
    id: '/packing',
    path: '/packing',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsNutriAuditRoute =
  AuthenticatedFoodcostUsNutriAuditRouteImport.update({
    id: '/nutri-audit',
    path: '/nutri-audit',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsMissingRecipesRoute =
  AuthenticatedFoodcostUsMissingRecipesRouteImport.update({
    id: '/missing-recipes',
    path: '/missing-recipes',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsMenuCostingRoute =
  AuthenticatedFoodcostUsMenuCostingRouteImport.update({
    id: '/menu-costing',
    path: '/menu-costing',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsMenuRoute =
  AuthenticatedFoodcostUsMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsIngredientsRoute =
  AuthenticatedFoodcostUsIngredientsRouteImport.update({
    id: '/ingredients',
    path: '/ingredients',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsFcAuditRoute =
  AuthenticatedFoodcostUsFcAuditRouteImport.update({
    id: '/fc-audit',
    path: '/fc-audit',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsCategoriesRoute =
  AuthenticatedFoodcostUsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsBrandsRoute =
  AuthenticatedFoodcostUsBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsBrandMasterRoute =
  AuthenticatedFoodcostUsBrandMasterRouteImport.update({
    id: '/brand-master',
    path: '/brand-master',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostUsAuditRoute =
  AuthenticatedFoodcostUsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedFoodcostUsRoute,
  } as any)
const AuthenticatedFoodcostRecipesRecipeIdRoute =
  AuthenticatedFoodcostRecipesRecipeIdRouteImport.update({
    id: '/recipes/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => AuthenticatedFoodcostRoute,
  } as any)
const AuthenticatedFoodcostPrepsIdRoute =
  AuthenticatedFoodcostPrepsIdRouteImport.update({
    id: '/preps/$id',
    path: '/preps/$id',
    getParentRoute: () => AuthenticatedFoodcostRoute,
  } as any)
const AuthenticatedFoodcostInReportsHubRoute =
  AuthenticatedFoodcostInReportsHubRouteImport.update({
    id: '/reports-hub',
    path: '/reports-hub',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInReportsRoute =
  AuthenticatedFoodcostInReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInRecipeVerifyRoute =
  AuthenticatedFoodcostInRecipeVerifyRouteImport.update({
    id: '/recipe-verify',
    path: '/recipe-verify',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInProductsRoute =
  AuthenticatedFoodcostInProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInPrepsRoute =
  AuthenticatedFoodcostInPrepsRouteImport.update({
    id: '/preps',
    path: '/preps',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInPrepReportsRoute =
  AuthenticatedFoodcostInPrepReportsRouteImport.update({
    id: '/prep-reports',
    path: '/prep-reports',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInPackingRoute =
  AuthenticatedFoodcostInPackingRouteImport.update({
    id: '/packing',
    path: '/packing',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInNutriAuditRoute =
  AuthenticatedFoodcostInNutriAuditRouteImport.update({
    id: '/nutri-audit',
    path: '/nutri-audit',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInMissingRecipesRoute =
  AuthenticatedFoodcostInMissingRecipesRouteImport.update({
    id: '/missing-recipes',
    path: '/missing-recipes',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInMenuCostingRoute =
  AuthenticatedFoodcostInMenuCostingRouteImport.update({
    id: '/menu-costing',
    path: '/menu-costing',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInMenuRoute =
  AuthenticatedFoodcostInMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInIngredientsRoute =
  AuthenticatedFoodcostInIngredientsRouteImport.update({
    id: '/ingredients',
    path: '/ingredients',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInFcAuditRoute =
  AuthenticatedFoodcostInFcAuditRouteImport.update({
    id: '/fc-audit',
    path: '/fc-audit',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInCategoriesRoute =
  AuthenticatedFoodcostInCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInBrandsRoute =
  AuthenticatedFoodcostInBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInBrandMasterRoute =
  AuthenticatedFoodcostInBrandMasterRouteImport.update({
    id: '/brand-master',
    path: '/brand-master',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedFoodcostInAuditRoute =
  AuthenticatedFoodcostInAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedFoodcostInRoute,
  } as any)
const AuthenticatedSftTrainingPhysicalVisitAssignVisitIdRoute =
  AuthenticatedSftTrainingPhysicalVisitAssignVisitIdRouteImport.update({
    id: '/assign/$visitId',
    path: '/assign/$visitId',
    getParentRoute: () => AuthenticatedSftTrainingPhysicalVisitRoute,
  } as any)
const AuthenticatedLearnCourseIdDayDayIdRoute =
  AuthenticatedLearnCourseIdDayDayIdRouteImport.update({
    id: '/day/$dayId',
    path: '/day/$dayId',
    getParentRoute: () => AuthenticatedLearnCourseIdRoute,
  } as any)
const AuthenticatedFoodcostCategoriesIdCrcRoute =
  AuthenticatedFoodcostCategoriesIdCrcRouteImport.update({
    id: '/categories/$id/crc',
    path: '/categories/$id/crc',
    getParentRoute: () => AuthenticatedFoodcostRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner-login': typeof PartnerLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/course': typeof AuthenticatedCourseRoute
  '/foodcost': typeof AuthenticatedFoodcostRouteWithChildren
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/sft-training': typeof AuthenticatedSftTrainingRouteWithChildren
  '/team-guide': typeof AuthenticatedTeamGuideRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/visitor/physical-visit': typeof VisitorPhysicalVisitRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/foodcost/in': typeof AuthenticatedFoodcostInRouteWithChildren
  '/foodcost/us': typeof AuthenticatedFoodcostUsRouteWithChildren
  '/learn/$courseId': typeof AuthenticatedLearnCourseIdRouteWithChildren
  '/partner/cook': typeof AuthenticatedPartnerCookRoute
  '/partner/downloads': typeof AuthenticatedPartnerDownloadsRoute
  '/partner/learn': typeof AuthenticatedPartnerLearnRoute
  '/partner/visit': typeof AuthenticatedPartnerVisitRoute
  '/sft-training/invite-certify': typeof AuthenticatedSftTrainingInviteCertifyRoute
  '/sft-training/partner-payments': typeof AuthenticatedSftTrainingPartnerPaymentsRoute
  '/sft-training/physical-visit': typeof AuthenticatedSftTrainingPhysicalVisitRouteWithChildren
  '/sft-training/program': typeof AuthenticatedSftTrainingProgramRoute
  '/sft-training/review': typeof AuthenticatedSftTrainingReviewRoute
  '/foodcost/': typeof AuthenticatedFoodcostIndexRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/partner/': typeof AuthenticatedPartnerIndexRoute
  '/sft-training/': typeof AuthenticatedSftTrainingIndexRoute
  '/foodcost/in/audit': typeof AuthenticatedFoodcostInAuditRoute
  '/foodcost/in/brand-master': typeof AuthenticatedFoodcostInBrandMasterRoute
  '/foodcost/in/brands': typeof AuthenticatedFoodcostInBrandsRoute
  '/foodcost/in/categories': typeof AuthenticatedFoodcostInCategoriesRoute
  '/foodcost/in/fc-audit': typeof AuthenticatedFoodcostInFcAuditRoute
  '/foodcost/in/ingredients': typeof AuthenticatedFoodcostInIngredientsRoute
  '/foodcost/in/menu': typeof AuthenticatedFoodcostInMenuRoute
  '/foodcost/in/menu-costing': typeof AuthenticatedFoodcostInMenuCostingRoute
  '/foodcost/in/missing-recipes': typeof AuthenticatedFoodcostInMissingRecipesRoute
  '/foodcost/in/nutri-audit': typeof AuthenticatedFoodcostInNutriAuditRoute
  '/foodcost/in/packing': typeof AuthenticatedFoodcostInPackingRoute
  '/foodcost/in/prep-reports': typeof AuthenticatedFoodcostInPrepReportsRoute
  '/foodcost/in/preps': typeof AuthenticatedFoodcostInPrepsRoute
  '/foodcost/in/products': typeof AuthenticatedFoodcostInProductsRoute
  '/foodcost/in/recipe-verify': typeof AuthenticatedFoodcostInRecipeVerifyRoute
  '/foodcost/in/reports': typeof AuthenticatedFoodcostInReportsRoute
  '/foodcost/in/reports-hub': typeof AuthenticatedFoodcostInReportsHubRoute
  '/foodcost/preps/$id': typeof AuthenticatedFoodcostPrepsIdRoute
  '/foodcost/recipes/$recipeId': typeof AuthenticatedFoodcostRecipesRecipeIdRoute
  '/foodcost/us/audit': typeof AuthenticatedFoodcostUsAuditRoute
  '/foodcost/us/brand-master': typeof AuthenticatedFoodcostUsBrandMasterRoute
  '/foodcost/us/brands': typeof AuthenticatedFoodcostUsBrandsRoute
  '/foodcost/us/categories': typeof AuthenticatedFoodcostUsCategoriesRoute
  '/foodcost/us/fc-audit': typeof AuthenticatedFoodcostUsFcAuditRoute
  '/foodcost/us/ingredients': typeof AuthenticatedFoodcostUsIngredientsRoute
  '/foodcost/us/menu': typeof AuthenticatedFoodcostUsMenuRoute
  '/foodcost/us/menu-costing': typeof AuthenticatedFoodcostUsMenuCostingRoute
  '/foodcost/us/missing-recipes': typeof AuthenticatedFoodcostUsMissingRecipesRoute
  '/foodcost/us/nutri-audit': typeof AuthenticatedFoodcostUsNutriAuditRoute
  '/foodcost/us/packing': typeof AuthenticatedFoodcostUsPackingRoute
  '/foodcost/us/prep-reports': typeof AuthenticatedFoodcostUsPrepReportsRoute
  '/foodcost/us/preps': typeof AuthenticatedFoodcostUsPrepsRoute
  '/foodcost/us/products': typeof AuthenticatedFoodcostUsProductsRoute
  '/foodcost/us/recipe-verify': typeof AuthenticatedFoodcostUsRecipeVerifyRoute
  '/foodcost/us/reports': typeof AuthenticatedFoodcostUsReportsRoute
  '/foodcost/us/reports-hub': typeof AuthenticatedFoodcostUsReportsHubRoute
  '/learn/$courseId/$moduleId': typeof AuthenticatedLearnCourseIdModuleIdRoute
  '/sft-training/courses/$courseId': typeof AuthenticatedSftTrainingCoursesCourseIdRoute
  '/sft-training/play/$courseId': typeof AuthenticatedSftTrainingPlayCourseIdRoute
  '/sft-training/teach/$courseId': typeof AuthenticatedSftTrainingTeachCourseIdRoute
  '/foodcost/categories/$id/crc': typeof AuthenticatedFoodcostCategoriesIdCrcRoute
  '/learn/$courseId/day/$dayId': typeof AuthenticatedLearnCourseIdDayDayIdRoute
  '/sft-training/physical-visit/assign/$visitId': typeof AuthenticatedSftTrainingPhysicalVisitAssignVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner-login': typeof PartnerLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/course': typeof AuthenticatedCourseRoute
  '/team-guide': typeof AuthenticatedTeamGuideRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/visitor/physical-visit': typeof VisitorPhysicalVisitRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/foodcost/in': typeof AuthenticatedFoodcostInRouteWithChildren
  '/foodcost/us': typeof AuthenticatedFoodcostUsRouteWithChildren
  '/learn/$courseId': typeof AuthenticatedLearnCourseIdRouteWithChildren
  '/partner/cook': typeof AuthenticatedPartnerCookRoute
  '/partner/downloads': typeof AuthenticatedPartnerDownloadsRoute
  '/partner/learn': typeof AuthenticatedPartnerLearnRoute
  '/partner/visit': typeof AuthenticatedPartnerVisitRoute
  '/sft-training/invite-certify': typeof AuthenticatedSftTrainingInviteCertifyRoute
  '/sft-training/partner-payments': typeof AuthenticatedSftTrainingPartnerPaymentsRoute
  '/sft-training/physical-visit': typeof AuthenticatedSftTrainingPhysicalVisitRouteWithChildren
  '/sft-training/program': typeof AuthenticatedSftTrainingProgramRoute
  '/sft-training/review': typeof AuthenticatedSftTrainingReviewRoute
  '/foodcost': typeof AuthenticatedFoodcostIndexRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/partner': typeof AuthenticatedPartnerIndexRoute
  '/sft-training': typeof AuthenticatedSftTrainingIndexRoute
  '/foodcost/in/audit': typeof AuthenticatedFoodcostInAuditRoute
  '/foodcost/in/brand-master': typeof AuthenticatedFoodcostInBrandMasterRoute
  '/foodcost/in/brands': typeof AuthenticatedFoodcostInBrandsRoute
  '/foodcost/in/categories': typeof AuthenticatedFoodcostInCategoriesRoute
  '/foodcost/in/fc-audit': typeof AuthenticatedFoodcostInFcAuditRoute
  '/foodcost/in/ingredients': typeof AuthenticatedFoodcostInIngredientsRoute
  '/foodcost/in/menu': typeof AuthenticatedFoodcostInMenuRoute
  '/foodcost/in/menu-costing': typeof AuthenticatedFoodcostInMenuCostingRoute
  '/foodcost/in/missing-recipes': typeof AuthenticatedFoodcostInMissingRecipesRoute
  '/foodcost/in/nutri-audit': typeof AuthenticatedFoodcostInNutriAuditRoute
  '/foodcost/in/packing': typeof AuthenticatedFoodcostInPackingRoute
  '/foodcost/in/prep-reports': typeof AuthenticatedFoodcostInPrepReportsRoute
  '/foodcost/in/preps': typeof AuthenticatedFoodcostInPrepsRoute
  '/foodcost/in/products': typeof AuthenticatedFoodcostInProductsRoute
  '/foodcost/in/recipe-verify': typeof AuthenticatedFoodcostInRecipeVerifyRoute
  '/foodcost/in/reports': typeof AuthenticatedFoodcostInReportsRoute
  '/foodcost/in/reports-hub': typeof AuthenticatedFoodcostInReportsHubRoute
  '/foodcost/preps/$id': typeof AuthenticatedFoodcostPrepsIdRoute
  '/foodcost/recipes/$recipeId': typeof AuthenticatedFoodcostRecipesRecipeIdRoute
  '/foodcost/us/audit': typeof AuthenticatedFoodcostUsAuditRoute
  '/foodcost/us/brand-master': typeof AuthenticatedFoodcostUsBrandMasterRoute
  '/foodcost/us/brands': typeof AuthenticatedFoodcostUsBrandsRoute
  '/foodcost/us/categories': typeof AuthenticatedFoodcostUsCategoriesRoute
  '/foodcost/us/fc-audit': typeof AuthenticatedFoodcostUsFcAuditRoute
  '/foodcost/us/ingredients': typeof AuthenticatedFoodcostUsIngredientsRoute
  '/foodcost/us/menu': typeof AuthenticatedFoodcostUsMenuRoute
  '/foodcost/us/menu-costing': typeof AuthenticatedFoodcostUsMenuCostingRoute
  '/foodcost/us/missing-recipes': typeof AuthenticatedFoodcostUsMissingRecipesRoute
  '/foodcost/us/nutri-audit': typeof AuthenticatedFoodcostUsNutriAuditRoute
  '/foodcost/us/packing': typeof AuthenticatedFoodcostUsPackingRoute
  '/foodcost/us/prep-reports': typeof AuthenticatedFoodcostUsPrepReportsRoute
  '/foodcost/us/preps': typeof AuthenticatedFoodcostUsPrepsRoute
  '/foodcost/us/products': typeof AuthenticatedFoodcostUsProductsRoute
  '/foodcost/us/recipe-verify': typeof AuthenticatedFoodcostUsRecipeVerifyRoute
  '/foodcost/us/reports': typeof AuthenticatedFoodcostUsReportsRoute
  '/foodcost/us/reports-hub': typeof AuthenticatedFoodcostUsReportsHubRoute
  '/learn/$courseId/$moduleId': typeof AuthenticatedLearnCourseIdModuleIdRoute
  '/sft-training/courses/$courseId': typeof AuthenticatedSftTrainingCoursesCourseIdRoute
  '/sft-training/play/$courseId': typeof AuthenticatedSftTrainingPlayCourseIdRoute
  '/sft-training/teach/$courseId': typeof AuthenticatedSftTrainingTeachCourseIdRoute
  '/foodcost/categories/$id/crc': typeof AuthenticatedFoodcostCategoriesIdCrcRoute
  '/learn/$courseId/day/$dayId': typeof AuthenticatedLearnCourseIdDayDayIdRoute
  '/sft-training/physical-visit/assign/$visitId': typeof AuthenticatedSftTrainingPhysicalVisitAssignVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/partner-login': typeof PartnerLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/course': typeof AuthenticatedCourseRoute
  '/_authenticated/foodcost': typeof AuthenticatedFoodcostRouteWithChildren
  '/_authenticated/learn': typeof AuthenticatedLearnRouteWithChildren
  '/_authenticated/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/_authenticated/sft-training': typeof AuthenticatedSftTrainingRouteWithChildren
  '/_authenticated/team-guide': typeof AuthenticatedTeamGuideRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/visitor/physical-visit': typeof VisitorPhysicalVisitRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/foodcost/in': typeof AuthenticatedFoodcostInRouteWithChildren
  '/_authenticated/foodcost/us': typeof AuthenticatedFoodcostUsRouteWithChildren
  '/_authenticated/learn/$courseId': typeof AuthenticatedLearnCourseIdRouteWithChildren
  '/_authenticated/partner/cook': typeof AuthenticatedPartnerCookRoute
  '/_authenticated/partner/downloads': typeof AuthenticatedPartnerDownloadsRoute
  '/_authenticated/partner/learn': typeof AuthenticatedPartnerLearnRoute
  '/_authenticated/partner/visit': typeof AuthenticatedPartnerVisitRoute
  '/_authenticated/sft-training/invite-certify': typeof AuthenticatedSftTrainingInviteCertifyRoute
  '/_authenticated/sft-training/partner-payments': typeof AuthenticatedSftTrainingPartnerPaymentsRoute
  '/_authenticated/sft-training/physical-visit': typeof AuthenticatedSftTrainingPhysicalVisitRouteWithChildren
  '/_authenticated/sft-training/program': typeof AuthenticatedSftTrainingProgramRoute
  '/_authenticated/sft-training/review': typeof AuthenticatedSftTrainingReviewRoute
  '/_authenticated/foodcost/': typeof AuthenticatedFoodcostIndexRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/partner/': typeof AuthenticatedPartnerIndexRoute
  '/_authenticated/sft-training/': typeof AuthenticatedSftTrainingIndexRoute
  '/_authenticated/foodcost/in/audit': typeof AuthenticatedFoodcostInAuditRoute
  '/_authenticated/foodcost/in/brand-master': typeof AuthenticatedFoodcostInBrandMasterRoute
  '/_authenticated/foodcost/in/brands': typeof AuthenticatedFoodcostInBrandsRoute
  '/_authenticated/foodcost/in/categories': typeof AuthenticatedFoodcostInCategoriesRoute
  '/_authenticated/foodcost/in/fc-audit': typeof AuthenticatedFoodcostInFcAuditRoute
  '/_authenticated/foodcost/in/ingredients': typeof AuthenticatedFoodcostInIngredientsRoute
  '/_authenticated/foodcost/in/menu': typeof AuthenticatedFoodcostInMenuRoute
  '/_authenticated/foodcost/in/menu-costing': typeof AuthenticatedFoodcostInMenuCostingRoute
  '/_authenticated/foodcost/in/missing-recipes': typeof AuthenticatedFoodcostInMissingRecipesRoute
  '/_authenticated/foodcost/in/nutri-audit': typeof AuthenticatedFoodcostInNutriAuditRoute
  '/_authenticated/foodcost/in/packing': typeof AuthenticatedFoodcostInPackingRoute
  '/_authenticated/foodcost/in/prep-reports': typeof AuthenticatedFoodcostInPrepReportsRoute
  '/_authenticated/foodcost/in/preps': typeof AuthenticatedFoodcostInPrepsRoute
  '/_authenticated/foodcost/in/products': typeof AuthenticatedFoodcostInProductsRoute
  '/_authenticated/foodcost/in/recipe-verify': typeof AuthenticatedFoodcostInRecipeVerifyRoute
  '/_authenticated/foodcost/in/reports': typeof AuthenticatedFoodcostInReportsRoute
  '/_authenticated/foodcost/in/reports-hub': typeof AuthenticatedFoodcostInReportsHubRoute
  '/_authenticated/foodcost/preps/$id': typeof AuthenticatedFoodcostPrepsIdRoute
  '/_authenticated/foodcost/recipes/$recipeId': typeof AuthenticatedFoodcostRecipesRecipeIdRoute
  '/_authenticated/foodcost/us/audit': typeof AuthenticatedFoodcostUsAuditRoute
  '/_authenticated/foodcost/us/brand-master': typeof AuthenticatedFoodcostUsBrandMasterRoute
  '/_authenticated/foodcost/us/brands': typeof AuthenticatedFoodcostUsBrandsRoute
  '/_authenticated/foodcost/us/categories': typeof AuthenticatedFoodcostUsCategoriesRoute
  '/_authenticated/foodcost/us/fc-audit': typeof AuthenticatedFoodcostUsFcAuditRoute
  '/_authenticated/foodcost/us/ingredients': typeof AuthenticatedFoodcostUsIngredientsRoute
  '/_authenticated/foodcost/us/menu': typeof AuthenticatedFoodcostUsMenuRoute
  '/_authenticated/foodcost/us/menu-costing': typeof AuthenticatedFoodcostUsMenuCostingRoute
  '/_authenticated/foodcost/us/missing-recipes': typeof AuthenticatedFoodcostUsMissingRecipesRoute
  '/_authenticated/foodcost/us/nutri-audit': typeof AuthenticatedFoodcostUsNutriAuditRoute
  '/_authenticated/foodcost/us/packing': typeof AuthenticatedFoodcostUsPackingRoute
  '/_authenticated/foodcost/us/prep-reports': typeof AuthenticatedFoodcostUsPrepReportsRoute
  '/_authenticated/foodcost/us/preps': typeof AuthenticatedFoodcostUsPrepsRoute
  '/_authenticated/foodcost/us/products': typeof AuthenticatedFoodcostUsProductsRoute
  '/_authenticated/foodcost/us/recipe-verify': typeof AuthenticatedFoodcostUsRecipeVerifyRoute
  '/_authenticated/foodcost/us/reports': typeof AuthenticatedFoodcostUsReportsRoute
  '/_authenticated/foodcost/us/reports-hub': typeof AuthenticatedFoodcostUsReportsHubRoute
  '/_authenticated/learn/$courseId/$moduleId': typeof AuthenticatedLearnCourseIdModuleIdRoute
  '/_authenticated/sft-training/courses/$courseId': typeof AuthenticatedSftTrainingCoursesCourseIdRoute
  '/_authenticated/sft-training/play/$courseId': typeof AuthenticatedSftTrainingPlayCourseIdRoute
  '/_authenticated/sft-training/teach/$courseId': typeof AuthenticatedSftTrainingTeachCourseIdRoute
  '/_authenticated/foodcost/categories/$id/crc': typeof AuthenticatedFoodcostCategoriesIdCrcRoute
  '/_authenticated/learn/$courseId/day/$dayId': typeof AuthenticatedLearnCourseIdDayDayIdRoute
  '/_authenticated/sft-training/physical-visit/assign/$visitId': typeof AuthenticatedSftTrainingPhysicalVisitAssignVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/partner-login'
    | '/reset-password'
    | '/unsubscribe'
    | '/course'
    | '/foodcost'
    | '/learn'
    | '/partner'
    | '/sft-training'
    | '/team-guide'
    | '/email/unsubscribe'
    | '/visitor/physical-visit'
    | '/admin/users'
    | '/foodcost/in'
    | '/foodcost/us'
    | '/learn/$courseId'
    | '/partner/cook'
    | '/partner/downloads'
    | '/partner/learn'
    | '/partner/visit'
    | '/sft-training/invite-certify'
    | '/sft-training/partner-payments'
    | '/sft-training/physical-visit'
    | '/sft-training/program'
    | '/sft-training/review'
    | '/foodcost/'
    | '/learn/'
    | '/partner/'
    | '/sft-training/'
    | '/foodcost/in/audit'
    | '/foodcost/in/brand-master'
    | '/foodcost/in/brands'
    | '/foodcost/in/categories'
    | '/foodcost/in/fc-audit'
    | '/foodcost/in/ingredients'
    | '/foodcost/in/menu'
    | '/foodcost/in/menu-costing'
    | '/foodcost/in/missing-recipes'
    | '/foodcost/in/nutri-audit'
    | '/foodcost/in/packing'
    | '/foodcost/in/prep-reports'
    | '/foodcost/in/preps'
    | '/foodcost/in/products'
    | '/foodcost/in/recipe-verify'
    | '/foodcost/in/reports'
    | '/foodcost/in/reports-hub'
    | '/foodcost/preps/$id'
    | '/foodcost/recipes/$recipeId'
    | '/foodcost/us/audit'
    | '/foodcost/us/brand-master'
    | '/foodcost/us/brands'
    | '/foodcost/us/categories'
    | '/foodcost/us/fc-audit'
    | '/foodcost/us/ingredients'
    | '/foodcost/us/menu'
    | '/foodcost/us/menu-costing'
    | '/foodcost/us/missing-recipes'
    | '/foodcost/us/nutri-audit'
    | '/foodcost/us/packing'
    | '/foodcost/us/prep-reports'
    | '/foodcost/us/preps'
    | '/foodcost/us/products'
    | '/foodcost/us/recipe-verify'
    | '/foodcost/us/reports'
    | '/foodcost/us/reports-hub'
    | '/learn/$courseId/$moduleId'
    | '/sft-training/courses/$courseId'
    | '/sft-training/play/$courseId'
    | '/sft-training/teach/$courseId'
    | '/foodcost/categories/$id/crc'
    | '/learn/$courseId/day/$dayId'
    | '/sft-training/physical-visit/assign/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/partner-login'
    | '/reset-password'
    | '/unsubscribe'
    | '/course'
    | '/team-guide'
    | '/email/unsubscribe'
    | '/visitor/physical-visit'
    | '/admin/users'
    | '/foodcost/in'
    | '/foodcost/us'
    | '/learn/$courseId'
    | '/partner/cook'
    | '/partner/downloads'
    | '/partner/learn'
    | '/partner/visit'
    | '/sft-training/invite-certify'
    | '/sft-training/partner-payments'
    | '/sft-training/physical-visit'
    | '/sft-training/program'
    | '/sft-training/review'
    | '/foodcost'
    | '/learn'
    | '/partner'
    | '/sft-training'
    | '/foodcost/in/audit'
    | '/foodcost/in/brand-master'
    | '/foodcost/in/brands'
    | '/foodcost/in/categories'
    | '/foodcost/in/fc-audit'
    | '/foodcost/in/ingredients'
    | '/foodcost/in/menu'
    | '/foodcost/in/menu-costing'
    | '/foodcost/in/missing-recipes'
    | '/foodcost/in/nutri-audit'
    | '/foodcost/in/packing'
    | '/foodcost/in/prep-reports'
    | '/foodcost/in/preps'
    | '/foodcost/in/products'
    | '/foodcost/in/recipe-verify'
    | '/foodcost/in/reports'
    | '/foodcost/in/reports-hub'
    | '/foodcost/preps/$id'
    | '/foodcost/recipes/$recipeId'
    | '/foodcost/us/audit'
    | '/foodcost/us/brand-master'
    | '/foodcost/us/brands'
    | '/foodcost/us/categories'
    | '/foodcost/us/fc-audit'
    | '/foodcost/us/ingredients'
    | '/foodcost/us/menu'
    | '/foodcost/us/menu-costing'
    | '/foodcost/us/missing-recipes'
    | '/foodcost/us/nutri-audit'
    | '/foodcost/us/packing'
    | '/foodcost/us/prep-reports'
    | '/foodcost/us/preps'
    | '/foodcost/us/products'
    | '/foodcost/us/recipe-verify'
    | '/foodcost/us/reports'
    | '/foodcost/us/reports-hub'
    | '/learn/$courseId/$moduleId'
    | '/sft-training/courses/$courseId'
    | '/sft-training/play/$courseId'
    | '/sft-training/teach/$courseId'
    | '/foodcost/categories/$id/crc'
    | '/learn/$courseId/day/$dayId'
    | '/sft-training/physical-visit/assign/$visitId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/partner-login'
    | '/reset-password'
    | '/unsubscribe'
    | '/_authenticated/course'
    | '/_authenticated/foodcost'
    | '/_authenticated/learn'
    | '/_authenticated/partner'
    | '/_authenticated/sft-training'
    | '/_authenticated/team-guide'
    | '/email/unsubscribe'
    | '/visitor/physical-visit'
    | '/_authenticated/admin/users'
    | '/_authenticated/foodcost/in'
    | '/_authenticated/foodcost/us'
    | '/_authenticated/learn/$courseId'
    | '/_authenticated/partner/cook'
    | '/_authenticated/partner/downloads'
    | '/_authenticated/partner/learn'
    | '/_authenticated/partner/visit'
    | '/_authenticated/sft-training/invite-certify'
    | '/_authenticated/sft-training/partner-payments'
    | '/_authenticated/sft-training/physical-visit'
    | '/_authenticated/sft-training/program'
    | '/_authenticated/sft-training/review'
    | '/_authenticated/foodcost/'
    | '/_authenticated/learn/'
    | '/_authenticated/partner/'
    | '/_authenticated/sft-training/'
    | '/_authenticated/foodcost/in/audit'
    | '/_authenticated/foodcost/in/brand-master'
    | '/_authenticated/foodcost/in/brands'
    | '/_authenticated/foodcost/in/categories'
    | '/_authenticated/foodcost/in/fc-audit'
    | '/_authenticated/foodcost/in/ingredients'
    | '/_authenticated/foodcost/in/menu'
    | '/_authenticated/foodcost/in/menu-costing'
    | '/_authenticated/foodcost/in/missing-recipes'
    | '/_authenticated/foodcost/in/nutri-audit'
    | '/_authenticated/foodcost/in/packing'
    | '/_authenticated/foodcost/in/prep-reports'
    | '/_authenticated/foodcost/in/preps'
    | '/_authenticated/foodcost/in/products'
    | '/_authenticated/foodcost/in/recipe-verify'
    | '/_authenticated/foodcost/in/reports'
    | '/_authenticated/foodcost/in/reports-hub'
    | '/_authenticated/foodcost/preps/$id'
    | '/_authenticated/foodcost/recipes/$recipeId'
    | '/_authenticated/foodcost/us/audit'
    | '/_authenticated/foodcost/us/brand-master'
    | '/_authenticated/foodcost/us/brands'
    | '/_authenticated/foodcost/us/categories'
    | '/_authenticated/foodcost/us/fc-audit'
    | '/_authenticated/foodcost/us/ingredients'
    | '/_authenticated/foodcost/us/menu'
    | '/_authenticated/foodcost/us/menu-costing'
    | '/_authenticated/foodcost/us/missing-recipes'
    | '/_authenticated/foodcost/us/nutri-audit'
    | '/_authenticated/foodcost/us/packing'
    | '/_authenticated/foodcost/us/prep-reports'
    | '/_authenticated/foodcost/us/preps'
    | '/_authenticated/foodcost/us/products'
    | '/_authenticated/foodcost/us/recipe-verify'
    | '/_authenticated/foodcost/us/reports'
    | '/_authenticated/foodcost/us/reports-hub'
    | '/_authenticated/learn/$courseId/$moduleId'
    | '/_authenticated/sft-training/courses/$courseId'
    | '/_authenticated/sft-training/play/$courseId'
    | '/_authenticated/sft-training/teach/$courseId'
    | '/_authenticated/foodcost/categories/$id/crc'
    | '/_authenticated/learn/$courseId/day/$dayId'
    | '/_authenticated/sft-training/physical-visit/assign/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PartnerLoginRoute: typeof PartnerLoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  VisitorPhysicalVisitRoute: typeof VisitorPhysicalVisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-login': {
      id: '/partner-login'
      path: '/partner-login'
      fullPath: '/partner-login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitor/physical-visit': {
      id: '/visitor/physical-visit'
      path: '/visitor/physical-visit'
      fullPath: '/visitor/physical-visit'
      preLoaderRoute: typeof VisitorPhysicalVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team-guide': {
      id: '/_authenticated/team-guide'
      path: '/team-guide'
      fullPath: '/team-guide'
      preLoaderRoute: typeof AuthenticatedTeamGuideRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sft-training': {
      id: '/_authenticated/sft-training'
      path: '/sft-training'
      fullPath: '/sft-training'
      preLoaderRoute: typeof AuthenticatedSftTrainingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/foodcost': {
      id: '/_authenticated/foodcost'
      path: '/foodcost'
      fullPath: '/foodcost'
      preLoaderRoute: typeof AuthenticatedFoodcostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/course': {
      id: '/_authenticated/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof AuthenticatedCourseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sft-training/': {
      id: '/_authenticated/sft-training/'
      path: '/'
      fullPath: '/sft-training/'
      preLoaderRoute: typeof AuthenticatedSftTrainingIndexRouteImport
      parentRoute: typeof AuthenticatedSftTrainingRoute
    }
    '/_authenticated/partner/': {
      id: '/_authenticated/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof AuthenticatedPartnerIndexRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/foodcost/': {
      id: '/_authenticated/foodcost/'
      path: '/'
      fullPath: '/foodcost/'
      preLoaderRoute: typeof AuthenticatedFoodcostIndexRouteImport
      parentRoute: typeof AuthenticatedFoodcostRoute
    }
    '/_authenticated/sft-training/review': {
      id: '/_authenticated/sft-training/review'
      path: '/review'
      fullPath: '/sft-training/review'
      preLoaderRoute: typeof AuthenticatedSftTrainingReviewRouteImport
      parentRoute: typeof AuthenticatedSftTrainingRoute
    }
    '/_authenticated/sft-training/program': {
      id: '/_authenticated/sft-training/program'
      path: '/program'
      fullPath: '/sft-training/program'
      preLoaderRoute: typeof AuthenticatedSftTrainingProgramRouteImport
      parentRoute: typeof AuthenticatedSftTrainingRoute
    }
    '/_authenticated/sft-training/physical-visit': {
      id: '/_authenticated/sft-training/physical-visit'
      path: '/physical-visit'
      fullPath: '/sft-training/physical-visit'
      preLoaderRoute: typeof AuthenticatedSftTrainingPhysicalVisitRouteImport
      parentRoute: typeof AuthenticatedSftTrainingRoute
    }
    '/_authenticated/sft-training/partner-payments': {
      id: '/_authenticated/sft-training/partner-payments'
      path: '/partner-payments'
      fullPath: '/sft-training/partner-payments'
      preLoaderRoute: typeof AuthenticatedSftTrainingPartnerPaymentsRouteImport
      parentRoute: typeof AuthenticatedSftTrainingRoute
    }
    '/_authenticated/sft-training/invite-certify': {
      id: '/_authenticated/sft-training/invite-certify'
      path: '/invite-certify'
      fullPath: '/sft-training/invite-certify'
      preLoaderRoute: typeof AuthenticatedSftTrainingInviteCertifyRouteImport
      parentRoute: typeof AuthenticatedSftTrainingRoute
    }
    '/_authenticated/partner/visit': {
      id: '/_authenticated/partner/visit'
      path: '/visit'
      fullPath: '/partner/visit'
      preLoaderRoute: typeof AuthenticatedPartnerVisitRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/learn': {
      id: '/_authenticated/partner/learn'
      path: '/learn'
      fullPath: '/partner/learn'
      preLoaderRoute: typeof AuthenticatedPartnerLearnRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/downloads': {
      id: '/_authenticated/partner/downloads'
      path: '/downloads'
      fullPath: '/partner/downloads'
      preLoaderRoute: typeof AuthenticatedPartnerDownloadsRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/cook': {
      id: '/_authenticated/partner/cook'
      path: '/cook'
      fullPath: '/partner/cook'
      preLoaderRoute: typeof AuthenticatedPartnerCookRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/learn/$courseId': {
      id: '/_authenticated/learn/$courseId'
      path: '/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof AuthenticatedLearnCourseIdRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/foodcost/us': {
      id: '/_authenticated/foodcost/us'
      path: '/us'
      fullPath: '/foodcost/us'
      preLoaderRoute: typeof AuthenticatedFoodcostUsRouteImport
      parentRoute: typeof AuthenticatedFoodcostRoute
    }
    '/_authenticated/foodcost/in': {
      id: '/_authenticated/foodcost/in'
      path: '/in'
      fullPath: '/foodcost/in'
      preLoaderRoute: typeof AuthenticatedFoodcostInRouteImport
      parentRoute: typeof AuthenticatedFoodcostRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sft-training/teach/$courseId': {
      id: '/_authenticated/sft-training/teach/$courseId'
      path: '/teach/$courseId'
      fullPath: '/sft-training/teach/$courseId'
      preLoaderRoute: typeof AuthenticatedSftTrainingTeachCourseIdRouteImport
      parentRoute: typeof AuthenticatedSftTrainingRoute
    }
    '/_authenticated/sft-training/play/$courseId': {
      id: '/_authenticated/sft-training/play/$courseId'
      path: '/play/$courseId'
      fullPath: '/sft-training/play/$courseId'
      preLoaderRoute: typeof AuthenticatedSftTrainingPlayCourseIdRouteImport
      parentRoute: typeof AuthenticatedSftTrainingRoute
    }
    '/_authenticated/sft-training/courses/$courseId': {
      id: '/_authenticated/sft-training/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/sft-training/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedSftTrainingCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedSftTrainingRoute
    }
    '/_authenticated/learn/$courseId/$moduleId': {
      id: '/_authenticated/learn/$courseId/$moduleId'
      path: '/$moduleId'
      fullPath: '/learn/$courseId/$moduleId'
      preLoaderRoute: typeof AuthenticatedLearnCourseIdModuleIdRouteImport
      parentRoute: typeof AuthenticatedLearnCourseIdRoute
    }
    '/_authenticated/foodcost/us/reports-hub': {
      id: '/_authenticated/foodcost/us/reports-hub'
      path: '/reports-hub'
      fullPath: '/foodcost/us/reports-hub'
      preLoaderRoute: typeof AuthenticatedFoodcostUsReportsHubRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/reports': {
      id: '/_authenticated/foodcost/us/reports'
      path: '/reports'
      fullPath: '/foodcost/us/reports'
      preLoaderRoute: typeof AuthenticatedFoodcostUsReportsRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/recipe-verify': {
      id: '/_authenticated/foodcost/us/recipe-verify'
      path: '/recipe-verify'
      fullPath: '/foodcost/us/recipe-verify'
      preLoaderRoute: typeof AuthenticatedFoodcostUsRecipeVerifyRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/products': {
      id: '/_authenticated/foodcost/us/products'
      path: '/products'
      fullPath: '/foodcost/us/products'
      preLoaderRoute: typeof AuthenticatedFoodcostUsProductsRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/preps': {
      id: '/_authenticated/foodcost/us/preps'
      path: '/preps'
      fullPath: '/foodcost/us/preps'
      preLoaderRoute: typeof AuthenticatedFoodcostUsPrepsRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/prep-reports': {
      id: '/_authenticated/foodcost/us/prep-reports'
      path: '/prep-reports'
      fullPath: '/foodcost/us/prep-reports'
      preLoaderRoute: typeof AuthenticatedFoodcostUsPrepReportsRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/packing': {
      id: '/_authenticated/foodcost/us/packing'
      path: '/packing'
      fullPath: '/foodcost/us/packing'
      preLoaderRoute: typeof AuthenticatedFoodcostUsPackingRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/nutri-audit': {
      id: '/_authenticated/foodcost/us/nutri-audit'
      path: '/nutri-audit'
      fullPath: '/foodcost/us/nutri-audit'
      preLoaderRoute: typeof AuthenticatedFoodcostUsNutriAuditRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/missing-recipes': {
      id: '/_authenticated/foodcost/us/missing-recipes'
      path: '/missing-recipes'
      fullPath: '/foodcost/us/missing-recipes'
      preLoaderRoute: typeof AuthenticatedFoodcostUsMissingRecipesRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/menu-costing': {
      id: '/_authenticated/foodcost/us/menu-costing'
      path: '/menu-costing'
      fullPath: '/foodcost/us/menu-costing'
      preLoaderRoute: typeof AuthenticatedFoodcostUsMenuCostingRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/menu': {
      id: '/_authenticated/foodcost/us/menu'
      path: '/menu'
      fullPath: '/foodcost/us/menu'
      preLoaderRoute: typeof AuthenticatedFoodcostUsMenuRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/ingredients': {
      id: '/_authenticated/foodcost/us/ingredients'
      path: '/ingredients'
      fullPath: '/foodcost/us/ingredients'
      preLoaderRoute: typeof AuthenticatedFoodcostUsIngredientsRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/fc-audit': {
      id: '/_authenticated/foodcost/us/fc-audit'
      path: '/fc-audit'
      fullPath: '/foodcost/us/fc-audit'
      preLoaderRoute: typeof AuthenticatedFoodcostUsFcAuditRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/categories': {
      id: '/_authenticated/foodcost/us/categories'
      path: '/categories'
      fullPath: '/foodcost/us/categories'
      preLoaderRoute: typeof AuthenticatedFoodcostUsCategoriesRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/brands': {
      id: '/_authenticated/foodcost/us/brands'
      path: '/brands'
      fullPath: '/foodcost/us/brands'
      preLoaderRoute: typeof AuthenticatedFoodcostUsBrandsRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/brand-master': {
      id: '/_authenticated/foodcost/us/brand-master'
      path: '/brand-master'
      fullPath: '/foodcost/us/brand-master'
      preLoaderRoute: typeof AuthenticatedFoodcostUsBrandMasterRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/us/audit': {
      id: '/_authenticated/foodcost/us/audit'
      path: '/audit'
      fullPath: '/foodcost/us/audit'
      preLoaderRoute: typeof AuthenticatedFoodcostUsAuditRouteImport
      parentRoute: typeof AuthenticatedFoodcostUsRoute
    }
    '/_authenticated/foodcost/recipes/$recipeId': {
      id: '/_authenticated/foodcost/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/foodcost/recipes/$recipeId'
      preLoaderRoute: typeof AuthenticatedFoodcostRecipesRecipeIdRouteImport
      parentRoute: typeof AuthenticatedFoodcostRoute
    }
    '/_authenticated/foodcost/preps/$id': {
      id: '/_authenticated/foodcost/preps/$id'
      path: '/preps/$id'
      fullPath: '/foodcost/preps/$id'
      preLoaderRoute: typeof AuthenticatedFoodcostPrepsIdRouteImport
      parentRoute: typeof AuthenticatedFoodcostRoute
    }
    '/_authenticated/foodcost/in/reports-hub': {
      id: '/_authenticated/foodcost/in/reports-hub'
      path: '/reports-hub'
      fullPath: '/foodcost/in/reports-hub'
      preLoaderRoute: typeof AuthenticatedFoodcostInReportsHubRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/reports': {
      id: '/_authenticated/foodcost/in/reports'
      path: '/reports'
      fullPath: '/foodcost/in/reports'
      preLoaderRoute: typeof AuthenticatedFoodcostInReportsRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/recipe-verify': {
      id: '/_authenticated/foodcost/in/recipe-verify'
      path: '/recipe-verify'
      fullPath: '/foodcost/in/recipe-verify'
      preLoaderRoute: typeof AuthenticatedFoodcostInRecipeVerifyRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/products': {
      id: '/_authenticated/foodcost/in/products'
      path: '/products'
      fullPath: '/foodcost/in/products'
      preLoaderRoute: typeof AuthenticatedFoodcostInProductsRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/preps': {
      id: '/_authenticated/foodcost/in/preps'
      path: '/preps'
      fullPath: '/foodcost/in/preps'
      preLoaderRoute: typeof AuthenticatedFoodcostInPrepsRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/prep-reports': {
      id: '/_authenticated/foodcost/in/prep-reports'
      path: '/prep-reports'
      fullPath: '/foodcost/in/prep-reports'
      preLoaderRoute: typeof AuthenticatedFoodcostInPrepReportsRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/packing': {
      id: '/_authenticated/foodcost/in/packing'
      path: '/packing'
      fullPath: '/foodcost/in/packing'
      preLoaderRoute: typeof AuthenticatedFoodcostInPackingRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/nutri-audit': {
      id: '/_authenticated/foodcost/in/nutri-audit'
      path: '/nutri-audit'
      fullPath: '/foodcost/in/nutri-audit'
      preLoaderRoute: typeof AuthenticatedFoodcostInNutriAuditRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/missing-recipes': {
      id: '/_authenticated/foodcost/in/missing-recipes'
      path: '/missing-recipes'
      fullPath: '/foodcost/in/missing-recipes'
      preLoaderRoute: typeof AuthenticatedFoodcostInMissingRecipesRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/menu-costing': {
      id: '/_authenticated/foodcost/in/menu-costing'
      path: '/menu-costing'
      fullPath: '/foodcost/in/menu-costing'
      preLoaderRoute: typeof AuthenticatedFoodcostInMenuCostingRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/menu': {
      id: '/_authenticated/foodcost/in/menu'
      path: '/menu'
      fullPath: '/foodcost/in/menu'
      preLoaderRoute: typeof AuthenticatedFoodcostInMenuRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/ingredients': {
      id: '/_authenticated/foodcost/in/ingredients'
      path: '/ingredients'
      fullPath: '/foodcost/in/ingredients'
      preLoaderRoute: typeof AuthenticatedFoodcostInIngredientsRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/fc-audit': {
      id: '/_authenticated/foodcost/in/fc-audit'
      path: '/fc-audit'
      fullPath: '/foodcost/in/fc-audit'
      preLoaderRoute: typeof AuthenticatedFoodcostInFcAuditRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/categories': {
      id: '/_authenticated/foodcost/in/categories'
      path: '/categories'
      fullPath: '/foodcost/in/categories'
      preLoaderRoute: typeof AuthenticatedFoodcostInCategoriesRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/brands': {
      id: '/_authenticated/foodcost/in/brands'
      path: '/brands'
      fullPath: '/foodcost/in/brands'
      preLoaderRoute: typeof AuthenticatedFoodcostInBrandsRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/brand-master': {
      id: '/_authenticated/foodcost/in/brand-master'
      path: '/brand-master'
      fullPath: '/foodcost/in/brand-master'
      preLoaderRoute: typeof AuthenticatedFoodcostInBrandMasterRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/foodcost/in/audit': {
      id: '/_authenticated/foodcost/in/audit'
      path: '/audit'
      fullPath: '/foodcost/in/audit'
      preLoaderRoute: typeof AuthenticatedFoodcostInAuditRouteImport
      parentRoute: typeof AuthenticatedFoodcostInRoute
    }
    '/_authenticated/sft-training/physical-visit/assign/$visitId': {
      id: '/_authenticated/sft-training/physical-visit/assign/$visitId'
      path: '/assign/$visitId'
      fullPath: '/sft-training/physical-visit/assign/$visitId'
      preLoaderRoute: typeof AuthenticatedSftTrainingPhysicalVisitAssignVisitIdRouteImport
      parentRoute: typeof AuthenticatedSftTrainingPhysicalVisitRoute
    }
    '/_authenticated/learn/$courseId/day/$dayId': {
      id: '/_authenticated/learn/$courseId/day/$dayId'
      path: '/day/$dayId'
      fullPath: '/learn/$courseId/day/$dayId'
      preLoaderRoute: typeof AuthenticatedLearnCourseIdDayDayIdRouteImport
      parentRoute: typeof AuthenticatedLearnCourseIdRoute
    }
    '/_authenticated/foodcost/categories/$id/crc': {
      id: '/_authenticated/foodcost/categories/$id/crc'
      path: '/categories/$id/crc'
      fullPath: '/foodcost/categories/$id/crc'
      preLoaderRoute: typeof AuthenticatedFoodcostCategoriesIdCrcRouteImport
      parentRoute: typeof AuthenticatedFoodcostRoute
    }
  }
}

interface AuthenticatedFoodcostInRouteChildren {
  AuthenticatedFoodcostInAuditRoute: typeof AuthenticatedFoodcostInAuditRoute
  AuthenticatedFoodcostInBrandMasterRoute: typeof AuthenticatedFoodcostInBrandMasterRoute
  AuthenticatedFoodcostInBrandsRoute: typeof AuthenticatedFoodcostInBrandsRoute
  AuthenticatedFoodcostInCategoriesRoute: typeof AuthenticatedFoodcostInCategoriesRoute
  AuthenticatedFoodcostInFcAuditRoute: typeof AuthenticatedFoodcostInFcAuditRoute
  AuthenticatedFoodcostInIngredientsRoute: typeof AuthenticatedFoodcostInIngredientsRoute
  AuthenticatedFoodcostInMenuRoute: typeof AuthenticatedFoodcostInMenuRoute
  AuthenticatedFoodcostInMenuCostingRoute: typeof AuthenticatedFoodcostInMenuCostingRoute
  AuthenticatedFoodcostInMissingRecipesRoute: typeof AuthenticatedFoodcostInMissingRecipesRoute
  AuthenticatedFoodcostInNutriAuditRoute: typeof AuthenticatedFoodcostInNutriAuditRoute
  AuthenticatedFoodcostInPackingRoute: typeof AuthenticatedFoodcostInPackingRoute
  AuthenticatedFoodcostInPrepReportsRoute: typeof AuthenticatedFoodcostInPrepReportsRoute
  AuthenticatedFoodcostInPrepsRoute: typeof AuthenticatedFoodcostInPrepsRoute
  AuthenticatedFoodcostInProductsRoute: typeof AuthenticatedFoodcostInProductsRoute
  AuthenticatedFoodcostInRecipeVerifyRoute: typeof AuthenticatedFoodcostInRecipeVerifyRoute
  AuthenticatedFoodcostInReportsRoute: typeof AuthenticatedFoodcostInReportsRoute
  AuthenticatedFoodcostInReportsHubRoute: typeof AuthenticatedFoodcostInReportsHubRoute
}

const AuthenticatedFoodcostInRouteChildren: AuthenticatedFoodcostInRouteChildren =
  {
    AuthenticatedFoodcostInAuditRoute: AuthenticatedFoodcostInAuditRoute,
    AuthenticatedFoodcostInBrandMasterRoute:
      AuthenticatedFoodcostInBrandMasterRoute,
    AuthenticatedFoodcostInBrandsRoute: AuthenticatedFoodcostInBrandsRoute,
    AuthenticatedFoodcostInCategoriesRoute:
      AuthenticatedFoodcostInCategoriesRoute,
    AuthenticatedFoodcostInFcAuditRoute: AuthenticatedFoodcostInFcAuditRoute,
    AuthenticatedFoodcostInIngredientsRoute:
      AuthenticatedFoodcostInIngredientsRoute,
    AuthenticatedFoodcostInMenuRoute: AuthenticatedFoodcostInMenuRoute,
    AuthenticatedFoodcostInMenuCostingRoute:
      AuthenticatedFoodcostInMenuCostingRoute,
    AuthenticatedFoodcostInMissingRecipesRoute:
      AuthenticatedFoodcostInMissingRecipesRoute,
    AuthenticatedFoodcostInNutriAuditRoute:
      AuthenticatedFoodcostInNutriAuditRoute,
    AuthenticatedFoodcostInPackingRoute: AuthenticatedFoodcostInPackingRoute,
    AuthenticatedFoodcostInPrepReportsRoute:
      AuthenticatedFoodcostInPrepReportsRoute,
    AuthenticatedFoodcostInPrepsRoute: AuthenticatedFoodcostInPrepsRoute,
    AuthenticatedFoodcostInProductsRoute: AuthenticatedFoodcostInProductsRoute,
    AuthenticatedFoodcostInRecipeVerifyRoute:
      AuthenticatedFoodcostInRecipeVerifyRoute,
    AuthenticatedFoodcostInReportsRoute: AuthenticatedFoodcostInReportsRoute,
    AuthenticatedFoodcostInReportsHubRoute:
      AuthenticatedFoodcostInReportsHubRoute,
  }

const AuthenticatedFoodcostInRouteWithChildren =
  AuthenticatedFoodcostInRoute._addFileChildren(
    AuthenticatedFoodcostInRouteChildren,
  )

interface AuthenticatedFoodcostUsRouteChildren {
  AuthenticatedFoodcostUsAuditRoute: typeof AuthenticatedFoodcostUsAuditRoute
  AuthenticatedFoodcostUsBrandMasterRoute: typeof AuthenticatedFoodcostUsBrandMasterRoute
  AuthenticatedFoodcostUsBrandsRoute: typeof AuthenticatedFoodcostUsBrandsRoute
  AuthenticatedFoodcostUsCategoriesRoute: typeof AuthenticatedFoodcostUsCategoriesRoute
  AuthenticatedFoodcostUsFcAuditRoute: typeof AuthenticatedFoodcostUsFcAuditRoute
  AuthenticatedFoodcostUsIngredientsRoute: typeof AuthenticatedFoodcostUsIngredientsRoute
  AuthenticatedFoodcostUsMenuRoute: typeof AuthenticatedFoodcostUsMenuRoute
  AuthenticatedFoodcostUsMenuCostingRoute: typeof AuthenticatedFoodcostUsMenuCostingRoute
  AuthenticatedFoodcostUsMissingRecipesRoute: typeof AuthenticatedFoodcostUsMissingRecipesRoute
  AuthenticatedFoodcostUsNutriAuditRoute: typeof AuthenticatedFoodcostUsNutriAuditRoute
  AuthenticatedFoodcostUsPackingRoute: typeof AuthenticatedFoodcostUsPackingRoute
  AuthenticatedFoodcostUsPrepReportsRoute: typeof AuthenticatedFoodcostUsPrepReportsRoute
  AuthenticatedFoodcostUsPrepsRoute: typeof AuthenticatedFoodcostUsPrepsRoute
  AuthenticatedFoodcostUsProductsRoute: typeof AuthenticatedFoodcostUsProductsRoute
  AuthenticatedFoodcostUsRecipeVerifyRoute: typeof AuthenticatedFoodcostUsRecipeVerifyRoute
  AuthenticatedFoodcostUsReportsRoute: typeof AuthenticatedFoodcostUsReportsRoute
  AuthenticatedFoodcostUsReportsHubRoute: typeof AuthenticatedFoodcostUsReportsHubRoute
}

const AuthenticatedFoodcostUsRouteChildren: AuthenticatedFoodcostUsRouteChildren =
  {
    AuthenticatedFoodcostUsAuditRoute: AuthenticatedFoodcostUsAuditRoute,
    AuthenticatedFoodcostUsBrandMasterRoute:
      AuthenticatedFoodcostUsBrandMasterRoute,
    AuthenticatedFoodcostUsBrandsRoute: AuthenticatedFoodcostUsBrandsRoute,
    AuthenticatedFoodcostUsCategoriesRoute:
      AuthenticatedFoodcostUsCategoriesRoute,
    AuthenticatedFoodcostUsFcAuditRoute: AuthenticatedFoodcostUsFcAuditRoute,
    AuthenticatedFoodcostUsIngredientsRoute:
      AuthenticatedFoodcostUsIngredientsRoute,
    AuthenticatedFoodcostUsMenuRoute: AuthenticatedFoodcostUsMenuRoute,
    AuthenticatedFoodcostUsMenuCostingRoute:
      AuthenticatedFoodcostUsMenuCostingRoute,
    AuthenticatedFoodcostUsMissingRecipesRoute:
      AuthenticatedFoodcostUsMissingRecipesRoute,
    AuthenticatedFoodcostUsNutriAuditRoute:
      AuthenticatedFoodcostUsNutriAuditRoute,
    AuthenticatedFoodcostUsPackingRoute: AuthenticatedFoodcostUsPackingRoute,
    AuthenticatedFoodcostUsPrepReportsRoute:
      AuthenticatedFoodcostUsPrepReportsRoute,
    AuthenticatedFoodcostUsPrepsRoute: AuthenticatedFoodcostUsPrepsRoute,
    AuthenticatedFoodcostUsProductsRoute: AuthenticatedFoodcostUsProductsRoute,
    AuthenticatedFoodcostUsRecipeVerifyRoute:
      AuthenticatedFoodcostUsRecipeVerifyRoute,
    AuthenticatedFoodcostUsReportsRoute: AuthenticatedFoodcostUsReportsRoute,
    AuthenticatedFoodcostUsReportsHubRoute:
      AuthenticatedFoodcostUsReportsHubRoute,
  }

const AuthenticatedFoodcostUsRouteWithChildren =
  AuthenticatedFoodcostUsRoute._addFileChildren(
    AuthenticatedFoodcostUsRouteChildren,
  )

interface AuthenticatedFoodcostRouteChildren {
  AuthenticatedFoodcostInRoute: typeof AuthenticatedFoodcostInRouteWithChildren
  AuthenticatedFoodcostUsRoute: typeof AuthenticatedFoodcostUsRouteWithChildren
  AuthenticatedFoodcostIndexRoute: typeof AuthenticatedFoodcostIndexRoute
  AuthenticatedFoodcostPrepsIdRoute: typeof AuthenticatedFoodcostPrepsIdRoute
  AuthenticatedFoodcostRecipesRecipeIdRoute: typeof AuthenticatedFoodcostRecipesRecipeIdRoute
  AuthenticatedFoodcostCategoriesIdCrcRoute: typeof AuthenticatedFoodcostCategoriesIdCrcRoute
}

const AuthenticatedFoodcostRouteChildren: AuthenticatedFoodcostRouteChildren = {
  AuthenticatedFoodcostInRoute: AuthenticatedFoodcostInRouteWithChildren,
  AuthenticatedFoodcostUsRoute: AuthenticatedFoodcostUsRouteWithChildren,
  AuthenticatedFoodcostIndexRoute: AuthenticatedFoodcostIndexRoute,
  AuthenticatedFoodcostPrepsIdRoute: AuthenticatedFoodcostPrepsIdRoute,
  AuthenticatedFoodcostRecipesRecipeIdRoute:
    AuthenticatedFoodcostRecipesRecipeIdRoute,
  AuthenticatedFoodcostCategoriesIdCrcRoute:
    AuthenticatedFoodcostCategoriesIdCrcRoute,
}

const AuthenticatedFoodcostRouteWithChildren =
  AuthenticatedFoodcostRoute._addFileChildren(
    AuthenticatedFoodcostRouteChildren,
  )

interface AuthenticatedLearnCourseIdRouteChildren {
  AuthenticatedLearnCourseIdModuleIdRoute: typeof AuthenticatedLearnCourseIdModuleIdRoute
  AuthenticatedLearnCourseIdDayDayIdRoute: typeof AuthenticatedLearnCourseIdDayDayIdRoute
}

const AuthenticatedLearnCourseIdRouteChildren: AuthenticatedLearnCourseIdRouteChildren =
  {
    AuthenticatedLearnCourseIdModuleIdRoute:
      AuthenticatedLearnCourseIdModuleIdRoute,
    AuthenticatedLearnCourseIdDayDayIdRoute:
      AuthenticatedLearnCourseIdDayDayIdRoute,
  }

const AuthenticatedLearnCourseIdRouteWithChildren =
  AuthenticatedLearnCourseIdRoute._addFileChildren(
    AuthenticatedLearnCourseIdRouteChildren,
  )

interface AuthenticatedLearnRouteChildren {
  AuthenticatedLearnCourseIdRoute: typeof AuthenticatedLearnCourseIdRouteWithChildren
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
}

const AuthenticatedLearnRouteChildren: AuthenticatedLearnRouteChildren = {
  AuthenticatedLearnCourseIdRoute: AuthenticatedLearnCourseIdRouteWithChildren,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
}

const AuthenticatedLearnRouteWithChildren =
  AuthenticatedLearnRoute._addFileChildren(AuthenticatedLearnRouteChildren)

interface AuthenticatedPartnerRouteChildren {
  AuthenticatedPartnerCookRoute: typeof AuthenticatedPartnerCookRoute
  AuthenticatedPartnerDownloadsRoute: typeof AuthenticatedPartnerDownloadsRoute
  AuthenticatedPartnerLearnRoute: typeof AuthenticatedPartnerLearnRoute
  AuthenticatedPartnerVisitRoute: typeof AuthenticatedPartnerVisitRoute
  AuthenticatedPartnerIndexRoute: typeof AuthenticatedPartnerIndexRoute
}

const AuthenticatedPartnerRouteChildren: AuthenticatedPartnerRouteChildren = {
  AuthenticatedPartnerCookRoute: AuthenticatedPartnerCookRoute,
  AuthenticatedPartnerDownloadsRoute: AuthenticatedPartnerDownloadsRoute,
  AuthenticatedPartnerLearnRoute: AuthenticatedPartnerLearnRoute,
  AuthenticatedPartnerVisitRoute: AuthenticatedPartnerVisitRoute,
  AuthenticatedPartnerIndexRoute: AuthenticatedPartnerIndexRoute,
}

const AuthenticatedPartnerRouteWithChildren =
  AuthenticatedPartnerRoute._addFileChildren(AuthenticatedPartnerRouteChildren)

interface AuthenticatedSftTrainingPhysicalVisitRouteChildren {
  AuthenticatedSftTrainingPhysicalVisitAssignVisitIdRoute: typeof AuthenticatedSftTrainingPhysicalVisitAssignVisitIdRoute
}

const AuthenticatedSftTrainingPhysicalVisitRouteChildren: AuthenticatedSftTrainingPhysicalVisitRouteChildren =
  {
    AuthenticatedSftTrainingPhysicalVisitAssignVisitIdRoute:
      AuthenticatedSftTrainingPhysicalVisitAssignVisitIdRoute,
  }

const AuthenticatedSftTrainingPhysicalVisitRouteWithChildren =
  AuthenticatedSftTrainingPhysicalVisitRoute._addFileChildren(
    AuthenticatedSftTrainingPhysicalVisitRouteChildren,
  )

interface AuthenticatedSftTrainingRouteChildren {
  AuthenticatedSftTrainingInviteCertifyRoute: typeof AuthenticatedSftTrainingInviteCertifyRoute
  AuthenticatedSftTrainingPartnerPaymentsRoute: typeof AuthenticatedSftTrainingPartnerPaymentsRoute
  AuthenticatedSftTrainingPhysicalVisitRoute: typeof AuthenticatedSftTrainingPhysicalVisitRouteWithChildren
  AuthenticatedSftTrainingProgramRoute: typeof AuthenticatedSftTrainingProgramRoute
  AuthenticatedSftTrainingReviewRoute: typeof AuthenticatedSftTrainingReviewRoute
  AuthenticatedSftTrainingIndexRoute: typeof AuthenticatedSftTrainingIndexRoute
  AuthenticatedSftTrainingCoursesCourseIdRoute: typeof AuthenticatedSftTrainingCoursesCourseIdRoute
  AuthenticatedSftTrainingPlayCourseIdRoute: typeof AuthenticatedSftTrainingPlayCourseIdRoute
  AuthenticatedSftTrainingTeachCourseIdRoute: typeof AuthenticatedSftTrainingTeachCourseIdRoute
}

const AuthenticatedSftTrainingRouteChildren: AuthenticatedSftTrainingRouteChildren =
  {
    AuthenticatedSftTrainingInviteCertifyRoute:
      AuthenticatedSftTrainingInviteCertifyRoute,
    AuthenticatedSftTrainingPartnerPaymentsRoute:
      AuthenticatedSftTrainingPartnerPaymentsRoute,
    AuthenticatedSftTrainingPhysicalVisitRoute:
      AuthenticatedSftTrainingPhysicalVisitRouteWithChildren,
    AuthenticatedSftTrainingProgramRoute: AuthenticatedSftTrainingProgramRoute,
    AuthenticatedSftTrainingReviewRoute: AuthenticatedSftTrainingReviewRoute,
    AuthenticatedSftTrainingIndexRoute: AuthenticatedSftTrainingIndexRoute,
    AuthenticatedSftTrainingCoursesCourseIdRoute:
      AuthenticatedSftTrainingCoursesCourseIdRoute,
    AuthenticatedSftTrainingPlayCourseIdRoute:
      AuthenticatedSftTrainingPlayCourseIdRoute,
    AuthenticatedSftTrainingTeachCourseIdRoute:
      AuthenticatedSftTrainingTeachCourseIdRoute,
  }

const AuthenticatedSftTrainingRouteWithChildren =
  AuthenticatedSftTrainingRoute._addFileChildren(
    AuthenticatedSftTrainingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCourseRoute: typeof AuthenticatedCourseRoute
  AuthenticatedFoodcostRoute: typeof AuthenticatedFoodcostRouteWithChildren
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRouteWithChildren
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRouteWithChildren
  AuthenticatedSftTrainingRoute: typeof AuthenticatedSftTrainingRouteWithChildren
  AuthenticatedTeamGuideRoute: typeof AuthenticatedTeamGuideRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCourseRoute: AuthenticatedCourseRoute,
  AuthenticatedFoodcostRoute: AuthenticatedFoodcostRouteWithChildren,
  AuthenticatedLearnRoute: AuthenticatedLearnRouteWithChildren,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRouteWithChildren,
  AuthenticatedSftTrainingRoute: AuthenticatedSftTrainingRouteWithChildren,
  AuthenticatedTeamGuideRoute: AuthenticatedTeamGuideRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PartnerLoginRoute: PartnerLoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  VisitorPhysicalVisitRoute: VisitorPhysicalVisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
